# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import comm.aggregation_server_pb2 as aggregation__server__pb2


class AggregationServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.fed_avg = channel.unary_unary(
                '/AggregationServerService/fed_avg',
                request_serializer=aggregation__server__pb2.local_params.SerializeToString,
                response_deserializer=aggregation__server__pb2.avg_params.FromString,
                )
        self.fed_shapley = channel.unary_unary(
                '/AggregationServerService/fed_shapley',
                request_serializer=aggregation__server__pb2.local_params.SerializeToString,
                response_deserializer=aggregation__server__pb2.avg_params.FromString,
                )


class AggregationServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def fed_avg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def fed_shapley(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AggregationServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'fed_avg': grpc.unary_unary_rpc_method_handler(
                    servicer.fed_avg,
                    request_deserializer=aggregation__server__pb2.local_params.FromString,
                    response_serializer=aggregation__server__pb2.avg_params.SerializeToString,
            ),
            'fed_shapley': grpc.unary_unary_rpc_method_handler(
                    servicer.fed_shapley,
                    request_deserializer=aggregation__server__pb2.local_params.FromString,
                    response_serializer=aggregation__server__pb2.avg_params.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AggregationServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AggregationServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def fed_avg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregationServerService/fed_avg',
            aggregation__server__pb2.local_params.SerializeToString,
            aggregation__server__pb2.avg_params.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def fed_shapley(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AggregationServerService/fed_shapley',
            aggregation__server__pb2.local_params.SerializeToString,
            aggregation__server__pb2.avg_params.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
