# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: aggregation_server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x61ggregation_server.proto\"K\n\x0clocal_params\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nsample_num\x18\x02 \x01(\x05\x12\x12\n\nparams_msg\x18\x03 \x01(\x0c\"5\n\navg_params\x12\x13\n\x0b\x63lient_rank\x18\x01 \x01(\x05\x12\x12\n\nparams_msg\x18\x02 \x01(\x0c\x32l\n\x18\x41ggregationServerService\x12%\n\x07\x66\x65\x64_avg\x12\r.local_params\x1a\x0b.avg_params\x12)\n\x0b\x66\x65\x64_shapley\x12\r.local_params\x1a\x0b.avg_paramsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'aggregation_server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOCAL_PARAMS._serialized_start=28
  _LOCAL_PARAMS._serialized_end=103
  _AVG_PARAMS._serialized_start=105
  _AVG_PARAMS._serialized_end=158
  _AGGREGATIONSERVERSERVICE._serialized_start=160
  _AGGREGATIONSERVERSERVICE._serialized_end=268
# @@protoc_insertion_point(module_scope)
